"""Wavepacket Configuration Interaction (WCI) — the geometrised FCI solver.

Based on the machine-verified wavepacket model (article 10.87 §6.03-05):
  - the ground state is a superposition of a small number (1-5 for STO-3G,
    ~10 for 6-31G chemical accuracy) of localised wavepackets on the
    Grassmannian;
  - a wavepacket = a centre determinant + its Bruhat 2-neighbourhood (all
    1-2 excitations, generated by H·centre);
  - the number of wavepackets grows sub-linearly with sector dimension
    (∝ log dim), far below the linear scaling of top-k power iteration.

Core algorithm (selected CI, wavepacket version):
  1. seed: the HF determinant as the first wavepacket centre;
  2. variational space = union of all wavepacket supports (cumulative,
     Bruhat-connected, only grows);
  3. Rayleigh-Ritz: build the dense H matrix in the variational space and
     diagonalise (the variational principle guarantees monotone convergence);
  4. residual r = H|ψ⟩ - E|ψ⟩;
  5. new wavepacket centre = the determinant outside the variational space
     with the largest residual component;
  6. repeat until converged.

Essential difference from top-k power iteration:
  - top-k re-selects k largest components each iteration; the support is
    unstructured and may split wavepackets, risking convergence to a wrong
    state;
  - WCI grows the variational space cumulatively (only adds, never removes);
    each added unit is a Bruhat-connected wavepacket.

Performance layers (verified on LiH/6-31G, dim=3025):
  1. searchsorted replaces dict lookup in H-matrix fill;
  2. incremental H-matrix build (reuse old block, only apply new states);
  3. float64 instead of complex128 (real-basis integrals → real symmetric
     H; eigh is ~17× faster on real symmetric matrices);
  4. incremental residual via cached H columns (H|D⟩ stored at H-build time,
     residual = column linear combination, no apply_fn Python loops);
  5. vectorised single-excitation enumeration in exterior.sparse_action_sz
     (precomputed term arrays replace the per-state Python nested loop).

Total speedup: 175s → 7.6s (23×) on LiH/6-31G.

Honest boundaries:
  - the SCF integrals are physical input (pyscf), not re-derived by geometry;
  - FCI reference energies are independent verification benchmarks;
  - the wavepacket model is empirically verified on four molecular systems
    (H₂/STO-3G, LiH/STO-3G, H₂O/STO-3G, LiH/6-31G); a formal proof of the
    sub-linear wavepacket scaling is an open geometric question.
"""

import time
import numpy as np
from itertools import combinations
from math import comb

try:
    from scipy.sparse.linalg import eigsh, LinearOperator
    _HAS_SCIPY = True
except ImportError:
    _HAS_SCIPY = False

# Threshold below which dense eigh is faster than Davidson (overhead of
# iterative method dominates for small matrices).
DAVIDSON_MIN_DIM = 300


# ---------------------------------------------------------------------------
# Geometric (Bruhat-distance) wavepacket centre selection
# ---------------------------------------------------------------------------
# The CIPSI-style "argmax |r_D|" selects the single determinant with the
# largest residual, but this determinant may lie inside the Bruhat 2-ball
# of an already-selected centre — the new wavepacket then heavily overlaps
# the existing one and adds little new information ("false convergence").
#
# Geometric cure: penalise candidates by their minimum Bruhat distance to
# already-selected centres.  Two determinants have Bruhat distance equal to
# the minimum number of excitations connecting them = popcount(az XOR) / 2
# + popcount(bz XOR) / 2.  Small distance ⇒ B(D,2) balls heavily overlap
# ⇒ low marginal information; large distance ⇒ complementary coverage.
#
# score(D) = |r_D|^2 / (1 + α · min_{D'∈centres} bruhat_dist(D, D'))
#
# This is a determinantal-point-process-style repulsive selection: the
# numerator keeps CIPSI's residual relevance, the denominator enforces
# geometric diversity.  α=0 recovers plain CIPSI; α→∞ enforces maximum
# diversity regardless of residual.

def _bruhat_dist_vec(cand_idx, center_idx, db, az_of, bz_of):
    """Vectorised minimum Bruhat distance from each candidate to any centre.

    Parameters
    ----------
    cand_idx : (M,) int array — candidate determinant combined indices
    center_idx : (K,) int array — already-selected centre combined indices
    db : int — beta-sector dimension (combined = alpha_rank * db + beta_rank)
    az_of, bz_of : arrays — rank → bitstring lookup tables

    Returns
    -------
    min_dist : (M,) int array — minimum Bruhat distance from each candidate
                to any centre (0 if candidate equals a centre).
    """
    if len(center_idx) == 0:
        return np.zeros(len(cand_idx), dtype=np.int64)
    # candidate bitstrings
    c_az = az_of[cand_idx // db]
    c_bz = bz_of[cand_idx % db]
    # centre bitstrings
    k_az = az_of[center_idx // db]
    k_bz = bz_of[center_idx % db]
    # For each candidate, compute min over centres of bruhat distance.
    # bruhat_dist = popcount(az_xor)//2 + popcount(bz_xor)//2
    # = (popcount(az_xor) + popcount(bz_xor)) // 2
    min_dist = np.full(len(cand_idx), 999, dtype=np.int64)
    for k in range(len(center_idx)):
        xor_az = c_az ^ k_az[k]
        xor_bz = c_bz ^ k_bz[k]
        # popcount via numpy (uint64 bit_count available in numpy 2.0+)
        try:
            pc_az = np.bitwise_count(xor_az.astype(np.uint64))
            pc_bz = np.bitwise_count(xor_bz.astype(np.uint64))
        except AttributeError:
            # fallback for older numpy
            pc_az = np.array([bin(int(x)).count('1') for x in xor_az], dtype=np.int64)
            pc_bz = np.array([bin(int(x)).count('1') for x in xor_bz], dtype=np.int64)
        dist = (pc_az + pc_bz) // 2
        min_dist = np.minimum(min_dist, dist)
    return min_dist


def _ball_cover_select(cand_idx, cand_r, apply_fn, unique_idx, db,
                       az_of, bz_of, rt_a, rt_b, top_k=100, batch_size=50):
    """Bruhat-ball greedy-cover wavepacket centre selection.

    Geometric cure for CIPSI's "false convergence": instead of argmax |r_D|
    (pick a *point*), pick the Bruhat ball B(D,2) that covers the largest
    *uncovered* residual weight.  A point with large residual but lying
    inside an already-covered ball adds little new information; the
    ball-cover score naturally penalises such picks.

    Algorithm:
      1. Take top-K candidates by |r_D|
      2. Batch apply_fn to get B(D,2) support for all candidates (in batches
         of batch_size to respect apply_fn's output buffer limit)
      3. For each ball, compute intersection with existing variational space
         via searchsorted
      4. uncovered_fraction = 1 - intersection / ball_size
      5. score(D) = |r_D|^2 * uncovered_fraction
      6. Return the candidate with max score

    Parameters
    ----------
    cand_idx : (M,) int array — candidate centre combined indices
    cand_r : (M,) float array — residual values at candidates
    apply_fn : callable — sparse_action_sz_vec apply function
    unique_idx : (V,) int array — existing variational space (sorted)
    db : int — beta-sector dimension
    az_of, bz_of, rt_a, rt_b : rank tables
    top_k : int — number of top candidates to consider (default 100)
    batch_size : int — apply_fn batch size (default 50, ~4M outputs/batch)

    Returns
    -------
    best_center : int — combined index of the selected centre
    best_score : float — ball-cover score of the selected centre
    best_local_idx : int — index in the top-K candidate list
    """
    import gc as _gc

    # 1. Take top-K candidates by |r_D|
    if len(cand_idx) > top_k:
        top_k_idx = np.argsort(-np.abs(cand_r))[:top_k]
        cand_idx = cand_idx[top_k_idx]
        cand_r = cand_r[top_k_idx]

    n_cand = len(cand_idx)
    scores = np.zeros(n_cand)
    ball_sizes = np.zeros(n_cand, dtype=np.int64)
    intersections = np.zeros(n_cand, dtype=np.int64)

    # 2. Batch apply_fn to get B(D,2) support
    for b0 in range(0, n_cand, batch_size):
        b1 = min(b0 + batch_size, n_cand)
        batch_cand = cand_idx[b0:b1]
        azs = az_of[batch_cand // db]
        bzs = bz_of[batch_cand % db]
        vals = np.ones(len(batch_cand), dtype=complex)
        result = apply_fn(azs, bzs, vals)
        if len(result) != 4:
            # fallback: plain CIPSI for this batch
            for i in range(b0, b1):
                scores[i] = abs(cand_r[i]) ** 2
            continue
        t_az, t_bz, t_v, src_idx = result
        # Convert target bitstrings to combined indices
        t_idx = rt_a.rank(t_az) * db + rt_b.rank(t_bz)
        del t_az, t_bz, t_v

        # 3. Group by local source index (0..batch_size-1)
        for local_s in range(len(batch_cand)):
            mask = src_idx == local_s
            ball_idx = t_idx[mask]
            ball_size = len(ball_idx)
            if ball_size == 0:
                continue
            global_i = b0 + local_s
            ball_sizes[global_i] = ball_size
            # Intersection with existing variational space via searchsorted
            pos = np.searchsorted(unique_idx, ball_idx)
            valid = pos < len(unique_idx)
            if valid.any():
                valid[valid] &= unique_idx[pos[valid]] == ball_idx[valid]
            inter = int(np.sum(valid))
            intersections[global_i] = inter
            uncovered_frac = 1.0 - inter / ball_size
            scores[global_i] = (abs(cand_r[global_i]) ** 2) * uncovered_frac

        del t_idx, src_idx, result
        _gc.collect()

    best_local = int(np.argmax(scores))
    best_center = int(cand_idx[best_local])
    best_score = float(scores[best_local])
    return best_center, best_score, best_local


def _davidson_ground(H_mat, tol=1e-8, max_iter=60, max_vecs=40):
    """Diagonally-preconditioned Davidson for the ground state.

    Much faster than implicitly-restarted Lanczos (scipy eigsh) for
    diagonally-dominant quantum-chemistry H matrices: the diagonal
    preconditioner t = -r / (H_ii - theta) gives far better correction
    directions than Lanczos' Krylov expansion, typically converging in
    10-20 matvecs vs 100+ for Lanczos.

    Algorithm:
      1. Start with orthonormal subspace V (random initial vectors)
      2. Project: T = V^T H V, diagonalise -> Ritz pairs (theta, s)
      3. Residual: r = H(Vs) - theta(Vs)
      4. Precondition: t = -r / (diag(H) - theta)
      5. Orthogonalise t against V, append to subspace
      6. Restart when subspace exceeds max_vecs (keep lowest Ritz vectors)
      7. Repeat until ||r|| < tol

    Parameters
    ----------
    H_mat : ndarray, shape (V, V)
        Real symmetric Hamiltonian matrix.
    tol : float
        Convergence tolerance on residual norm.
    max_iter : int
        Maximum Davidson iterations.
    max_vecs : int
        Maximum subspace size before restart.

    Returns
    -------
    E0 : float
        Ground-state energy.
    c0 : ndarray, shape (V,)
        Ground-state eigenvector.
    """
    V = H_mat.shape[0]
    h_diag = np.diag(H_mat)

    # Initial subspace: 3 random orthonormal vectors (seeded for reproducibility)
    rng = np.random.default_rng(42)
    n_init = min(3, V)
    V_vecs = rng.standard_normal((V, n_init))
    for i in range(n_init):
        for j in range(i):
            V_vecs[:, i] -= V_vecs[:, j] * (V_vecs[:, j] @ V_vecs[:, i])
        norm = np.linalg.norm(V_vecs[:, i])
        V_vecs[:, i] /= norm if norm > 1e-10 else 1.0

    HV = H_mat @ V_vecs  # precompute H*V (matvecs counted here)

    for iteration in range(max_iter):
        m = V_vecs.shape[1]
        # Projected Hamiltonian (small m×m, cheap)
        T = V_vecs.T @ HV
        theta, s = np.linalg.eigh(T)
        theta0 = float(theta[0])
        s0 = s[:, 0]

        # Ritz vector and residual (no extra matvec: HV = H*V)
        u = V_vecs @ s0
        r = HV @ s0 - theta0 * u
        r_norm = np.linalg.norm(r)

        if r_norm < tol:
            return theta0, u

        # Diagonal preconditioning (the key Davidson ingredient)
        denom = h_diag - theta0
        denom = np.where(np.abs(denom) < 1e-10, 1e-10, denom)
        t = -r / denom

        # Orthogonalise against current subspace (Modified Gram-Schmidt)
        for j in range(m):
            t -= V_vecs[:, j] * (V_vecs[:, j] @ t)
        t_norm = np.linalg.norm(t)
        if t_norm < 1e-10:
            # Fallback: random direction if preconditioned vector is in subspace
            t = rng.standard_normal(V)
            for j in range(m):
                t -= V_vecs[:, j] * (V_vecs[:, j] @ t)
            t_norm = np.linalg.norm(t)
            if t_norm < 1e-10:
                break
        t /= t_norm

        # Expand subspace
        V_vecs = np.hstack([V_vecs, t.reshape(-1, 1)])
        Ht = H_mat @ t  # one matvec per iteration
        HV = np.hstack([HV, Ht.reshape(-1, 1)])

        # Restart if subspace too large: keep lowest n_keep Ritz vectors
        if V_vecs.shape[1] > max_vecs:
            # Recompute projection with expanded subspace (after adding t)
            T = V_vecs.T @ HV
            theta_r, s_r = np.linalg.eigh(T)
            n_keep = max(10, max_vecs // 2)
            V_new = V_vecs @ s_r[:, :n_keep]
            HV_new = HV @ s_r[:, :n_keep]
            # Re-orthonormalise
            for i in range(n_keep):
                for j in range(i):
                    V_new[:, i] -= V_new[:, j] * (V_new[:, j] @ V_new[:, i])
                norm = np.linalg.norm(V_new[:, i])
                V_new[:, i] /= norm if norm > 1e-10 else 1.0
            V_vecs = V_new
            HV = HV_new

    # Final best estimate
    m = V_vecs.shape[1]
    T = V_vecs.T @ HV
    theta, s = np.linalg.eigh(T)
    u = V_vecs @ s[:, 0]
    return float(theta[0]), u


def _eigh_ground(H_mat, k=3, tol=1e-8, v0=None, gpu_H=None):
    """Ground-state eigenpair of a real symmetric H matrix.

    Uses scipy.sparse.linalg.eigsh (implicitly restarted Lanczos) for
    large matrices (V > DAVIDSON_MIN_DIM), falling back to dense
    np.linalg.eigh for small matrices where Lanczos overhead dominates.

    This replaces the O(V^3) dense diagonalisation with O(V^2 * n_iter)
    iterative diagonalisation — the single largest optimisation in WCI
    (profiling: dense eigh = 75% of total time on LiH/6-31G, V=1511).

    Parameters
    ----------
    H_mat : ndarray, shape (V, V)
        Real symmetric Hamiltonian matrix in the variational space.
    k : int
        Number of eigenpairs requested (must be < V-1 for eigsh).
    tol : float
        Convergence tolerance for eigsh.
    v0 : ndarray | None
        Initial guess vector for eigsh.
    gpu_H : GPUMatrix | None
        If provided, use GPU-accelerated matvec instead of H_mat @ x.
        H_mat is still needed for small-matrix fallback and shape info.

    Returns
    -------
    E0 : float
        Ground-state energy.
    c0 : ndarray, shape (V,)
        Ground-state eigenvector.
    """
    V = H_mat.shape[0]
    if not _HAS_SCIPY or V <= DAVIDSON_MIN_DIM:
        E_all, vecs = np.linalg.eigh(H_mat)
        return float(E_all[0]), vecs[:, 0]

    k_eff = min(k, V - 2)
    if gpu_H is not None:
        H_op = gpu_H.as_linear_operator()
    else:
        H_op = LinearOperator((V, V), matvec=lambda x: H_mat @ x, dtype=float)
    ncv = min(20, V)
    if v0 is None or len(v0) != V:
        v0 = np.ones(V) / np.sqrt(V)
    E, vecs = eigsh(H_op, k=k_eff, which='SA', tol=tol, v0=v0, ncv=ncv)
    idx = np.argmin(E)
    return float(E[idx]), vecs[:, idx]

__all__ = [
    "build_rank_tables", "apply_H", "Wavepacket",
    "build_variational_space", "build_H_matrix",
    "build_H_incremental", "compute_residual",
    "compute_residual_incremental", "wci",
    "compute_pt2_correction", "compute_block_pt2_correction",
]


# ---------------------------------------------------------------------------
# Rank tables (S_z sector: alpha/beta bitstring ↔ combined index)
# ---------------------------------------------------------------------------

def build_rank_tables(n_orb, n_a, n_b, da, db):
    """(rt_a, rt_b, az_of, bz_of) — the index maps for the S_z sector.

    rt_a[az] = alpha rank (or -1 if az has wrong popcount),
    rt_b[bz] = beta rank,
    az_of[i]  = alpha bitstring of rank i,
    bz_of[j]  = beta bitstring of rank j.
    Combined index = rt_a[az] * db + rt_b[bz]."""
    rt_a = np.full(1 << n_orb, -1, dtype=np.int64)
    rt_b = np.full(1 << n_orb, -1, dtype=np.int64)
    for i, c in enumerate(combinations(range(n_orb), n_a)):
        rt_a[sum(1 << j for j in c)] = i
    for i, c in enumerate(combinations(range(n_orb), n_b)):
        rt_b[sum(1 << j for j in c)] = i
    az_of = np.full(da, -1, dtype=np.int64)
    bz_of = np.full(db, -1, dtype=np.int64)
    for i, c in enumerate(combinations(range(n_orb), n_a)):
        az_of[i] = sum(1 << j for j in c)
    for i, c in enumerate(combinations(range(n_orb), n_b)):
        bz_of[i] = sum(1 << j for j in c)
    return rt_a, rt_b, az_of, bz_of


# ---------------------------------------------------------------------------
# Full H|ψ⟩ = apply (excitations + two-body diagonal) + hd_fn (one-body diag)
# ---------------------------------------------------------------------------

def apply_H(vals, idx, apply_fn, hd_fn, db, az_of, bz_of, rt_a, rt_b):
    """Full H|ψ⟩ on an arbitrary small support, returns (unique_target_idx,
    merged_vals).

    apply_fn gives the excitation terms (single/double) plus the two-body
    diagonal contribution; hd_fn gives the one-body diagonal.  The two are
    added on the unique target set.  Real-basis integrals → float64 output
    (eigh on real symmetric H is ~17× faster than complex Hermitian)."""
    azs = az_of[idx // db]
    bzs = bz_of[idx % db]
    result = apply_fn(azs, bzs, vals)
    if len(result) == 4:
        t_az, t_bz, t_v, _ = result  # vectorised version returns src_idx too
    else:
        t_az, t_bz, t_v = result
    t_idx = rt_a[t_az] * db + rt_b[t_bz]
    all_idx = np.concatenate([t_idx, idx])
    all_v = np.concatenate([np.asarray(t_v).real,
                             np.asarray(hd_fn(idx) * vals).real])
    u, inv = np.unique(all_idx, return_inverse=True)
    w = np.zeros(len(u), dtype=float)
    np.add.at(w, inv, all_v)
    return u, w


# ---------------------------------------------------------------------------
# Wavepacket
# ---------------------------------------------------------------------------

class Wavepacket:
    """A Bruhat 2-neighbourhood wavepacket centred at center_idx.

    Support = {centre} ∪ {all targets of apply(centre)} (1-2 excitations +
    two-body diagonal targets).  Because H is a 1+2-body operator, the
    targets of apply(centre) are exactly the states at Bruhat distance ≤ 2.

    couplings[D] = H_{D, centre} (the full diagonal of the centre is
    included as couplings[centre])."""

    def __init__(self, center_idx, apply_fn, hd_fn, db, az_of, bz_of,
                 rt_a, rt_b, max_size=None):
        self.center = int(center_idx)
        u, w = apply_H(np.array([1.0 + 0j]), np.array([self.center]),
                        apply_fn, hd_fn, db, az_of, bz_of, rt_a, rt_b)
        # Truncate to max_size strongest couplings if specified (large systems)
        if max_size is not None and len(u) > max_size:
            order = np.argsort(-np.abs(w))[:max_size]
            u = u[order]
            w = w[order]
        self.support = u
        self.size = len(u)
        self.couplings = dict(zip(u.tolist(), w.tolist()))

    def full_diagonal(self, state_idx):
        """Full diagonal E_D = H_{D,D} of the centre or a support state."""
        return self.couplings.get(int(state_idx), 0.0)


# ---------------------------------------------------------------------------
# Variational space and H matrix
# ---------------------------------------------------------------------------

def build_variational_space(wavepackets):
    """Union of all wavepacket supports, sorted and deduplicated."""
    all_idx = np.concatenate([wp.support for wp in wavepackets])
    return np.unique(all_idx)


def build_H_matrix(unique_idx, apply_fn, hd_fn, db, az_of, bz_of, rt_a,
                   rt_b, H_cols=None, chunk_size=500):
    """Memory-optimised H-matrix construction with chunked batch apply.

    Each chunk's apply_fn output is immediately written into H_mat and
    H_cols, then freed — peak memory is O(n^2) for the H matrix itself,
    not O(total_output_terms).  This avoids the OOM/swap timeout seen at
    >5000 states (2.4M output terms × 24 bytes ≈ 60GB peak).

    If H_cols is provided, the full column H|D_j⟩ (including out-of-space
    targets) is cached per-source for the incremental residual.

    Returns the dense real symmetric H matrix."""
    n = len(unique_idx)
    H_mat = np.zeros((n, n), dtype=float)

    # ---- chunked batch apply: fill H_mat per-chunk and free ----
    for c0 in range(0, n, chunk_size):
        c1 = min(c0 + chunk_size, n)
        chunk_idx = unique_idx[c0:c1]
        azs = az_of[chunk_idx // db]
        bzs = bz_of[chunk_idx % db]
        vals = np.ones(c1 - c0, dtype=complex)
        result = apply_fn(azs, bzs, vals)
        if len(result) == 4:
            t_az, t_bz, t_v, src_idx = result
        else:
            # fallback: scalar apply_fn (no src_idx) — process per-state
            from scipy.sparse import coo_matrix
            H_mat = np.zeros((n, n), dtype=float)
            for j in range(n):
                u, w = apply_H(np.array([1.0+0j]), np.array([unique_idx[j]]),
                               apply_fn, hd_fn, db, az_of, bz_of, rt_a, rt_b)
                if H_cols is not None:
                    H_cols[int(unique_idx[j])] = (u, w)
                pos = np.searchsorted(unique_idx, u)
                valid = pos < n
                if valid.any():
                    valid[valid] &= unique_idx[pos[valid]] == u[valid]
                np.add.at(H_mat, (pos[valid], j), w[valid])
            H_mat = (H_mat + H_mat.conj().T) / 2.0
            return H_mat

        t_idx = rt_a[t_az] * db + rt_b[t_bz]
        t_v = np.asarray(t_v).real
        src_global = src_idx + c0  # adjust to global source index

        # ---- fill H_mat for this chunk ----
        col_pos = src_global
        row_pos = np.searchsorted(unique_idx, t_idx)
        valid = row_pos < n
        if valid.any():
            valid[valid] &= unique_idx[row_pos[valid]] == t_idx[valid]
        np.add.at(H_mat, (row_pos[valid], col_pos[valid]), t_v[valid])

        # ---- cache H_cols for this chunk ----
        if H_cols is not None:
            order = np.argsort(src_global, kind='stable')
            s_src = src_global[order]
            s_idx = t_idx[order]
            s_v = t_v[order]
            # Filter: keep targets with |value| > threshold (both in-space and out-of-space)
            # This filters ~80% of tiny coefficients while preserving all significant couplings
            # for residual calculation (no need to recompute out-of-space residual)
            _sig = np.abs(s_v) > 1e-5
            s_idx = s_idx[_sig]
            s_v = s_v[_sig]
            s_src = s_src[_sig]
            boundaries = np.where(np.diff(s_src) != 0)[0] + 1
            starts = np.concatenate([[0], boundaries])
            ends = np.concatenate([boundaries, [len(s_src)]])
            for si in range(len(starts)):
                src = int(s_src[starts[si]])
                # Store copies (not views) so per-chunk arrays can be freed
                H_cols[int(unique_idx[src])] = (
                    s_idx[starts[si]:ends[si]].copy(),
                    s_v[starts[si]:ends[si]].copy())

        # free ALL temporary arrays for this chunk
        del t_az, t_bz, t_v, src_idx, t_idx, result, row_pos, valid
        del col_pos, src_global, chunk_idx, azs, bzs, vals
        if H_cols is not None:
            del order, s_src, s_idx, s_v, _sig
            del boundaries, starts, ends
        import gc; gc.collect()

    # ---- add diagonal terms (one-body + nuc; apply_fn gives two-body diag) ----
    diag_vals = np.asarray(hd_fn(unique_idx)).real
    np.add.at(H_mat, (np.arange(n), np.arange(n)), diag_vals)

    # ---- add diagonal to H_cols (one-body + nuc) ----
    if H_cols is not None:
        for j in range(n):
            key = int(unique_idx[j])
            if key in H_cols:
                prev_idx, prev_v = H_cols[key]
                H_cols[key] = (np.concatenate([prev_idx, [key]]),
                               np.concatenate([prev_v, [diag_vals[j]]]))
            else:
                H_cols[key] = (np.array([key], dtype=np.int64),
                               np.array([diag_vals[j]], dtype=float))

    # symmetrise (H is real symmetric; batch fill may have slight asymmetry
    # due to floating-point ordering of duplicate (row,col) entries)
    H_mat = (H_mat + H_mat.conj().T) / 2.0
    return H_mat


def build_H_incremental(unique_idx, unique_idx_prev, H_mat_prev,
                        apply_fn, hd_fn, db, az_of, bz_of, rt_a, rt_b,
                        H_cols=None, chunk_size=200):
    """Memory-optimised incremental H-matrix construction with chunked batch apply.

    Newly-added states are processed in chunks (like build_H_matrix) to avoid
    the OOM caused by a single apply_fn call over thousands of states
    (5000 states × 50k outputs = 250M terms = 6GB in one call).

    H_cols stores copies (not views) of |v|>1e-5 targets for both in-space
    and out-of-space couplings, enabling fast residual calculation without
    recomputing apply_fn."""
    import gc
    n = len(unique_idx)
    new_mask = ~np.isin(unique_idx, unique_idx_prev)
    new_positions = np.where(new_mask)[0]
    m = len(new_positions)
    if m == 0:
        return H_mat_prev

    H_mat = np.zeros((n, n), dtype=float)
    old_positions = np.where(~new_mask)[0]
    H_mat[np.ix_(old_positions, old_positions)] = H_mat_prev

    new_idx = unique_idx[new_positions]

    # ---- chunked batch apply for new states (avoids OOM) ----
    for c0 in range(0, m, chunk_size):
        c1 = min(c0 + chunk_size, m)
        chunk_new_idx = new_idx[c0:c1]
        chunk_positions = new_positions[c0:c1]
        azs = az_of[chunk_new_idx // db]
        bzs = bz_of[chunk_new_idx % db]
        vals = np.ones(c1 - c0, dtype=complex)
        result = apply_fn(azs, bzs, vals)
        if len(result) == 4:
            t_az, t_bz, t_v, src_idx = result
        else:
            t_az, t_bz, t_v = result
            src_idx = np.repeat(np.arange(c1 - c0, dtype=np.int32),
                                 np.array([len(t_az) // (c1 - c0)] * (c1 - c0)))

        t_idx = rt_a[t_az] * db + rt_b[t_bz]
        t_v = np.asarray(t_v).real
        src_global = src_idx.astype(np.int64) + c0  # index into new_idx

        # ---- fill H_mat columns for this chunk ----
        col_pos = new_positions[src_global]
        row_pos = np.searchsorted(unique_idx, t_idx)
        valid = row_pos < n
        if valid.any():
            valid[valid] &= unique_idx[row_pos[valid]] == t_idx[valid]
        np.add.at(H_mat, (row_pos[valid], col_pos[valid]), t_v[valid])

        # ---- cache H_cols for this chunk (|v|>1e-5, copies not views) ----
        if H_cols is not None:
            _sig = np.abs(t_v) > 1e-5
            _s_idx = t_idx[_sig]
            _s_v = t_v[_sig]
            _s_src = src_global[_sig]
            order = np.argsort(_s_src, kind='stable')
            _s_src = _s_src[order]
            _s_idx = _s_idx[order]
            _s_v = _s_v[order]
            boundaries = np.where(np.diff(_s_src) != 0)[0] + 1
            starts = np.concatenate([[0], boundaries])
            ends = np.concatenate([boundaries, [len(_s_src)]])
            for si in range(len(starts)):
                src = int(_s_src[starts[si]])
                H_cols[int(new_idx[src])] = (
                    _s_idx[starts[si]:ends[si]].copy(),
                    _s_v[starts[si]:ends[si]].copy())
            del _sig, _s_idx, _s_v, _s_src, order, boundaries, starts, ends

        # free temporary arrays for this chunk
        del t_az, t_bz, t_v, src_idx, t_idx, result, row_pos, valid
        del col_pos, src_global, chunk_new_idx, chunk_positions, azs, bzs, vals
        gc.collect()

    # ---- add diagonal terms for new states (one-body + nuc) ----
    diag_vals = np.asarray(hd_fn(new_idx)).real
    np.add.at(H_mat, (new_positions, new_positions), diag_vals)

    # ---- add diagonal to H_cols ----
    if H_cols is not None:
        for j in range(m):
            key = int(new_idx[j])
            if key in H_cols:
                prev_idx, prev_v = H_cols[key]
                H_cols[key] = (np.concatenate([prev_idx, [key]]),
                               np.concatenate([prev_v, [diag_vals[j]]]))
            else:
                H_cols[key] = (np.array([key], dtype=np.int64),
                               np.array([diag_vals[j]], dtype=float))

    # fill new rows from new columns by Hermiticity
    H_mat[new_positions, :] = H_mat[:, new_positions].conj().T
    return H_mat


# ---------------------------------------------------------------------------
# Residual
# ---------------------------------------------------------------------------

def compute_residual(coeffs, unique_idx, E, apply_fn, hd_fn, db,
                     az_of, bz_of, rt_a, rt_b):
    """Vectorised residual r = H|ψ⟩ - E|ψ⟩ (searchsorted, no dict lookup).

    Returns (r_in_norm, r_out_idx, r_out_vals) where r_in is the component
    inside the variational space and r_out is the component outside."""
    u, w = apply_H(coeffs, unique_idx, apply_fn, hd_fn, db,
                    az_of, bz_of, rt_a, rt_b)
    n = len(unique_idx)
    pos = np.searchsorted(unique_idx, u)
    in_space = pos < n
    if in_space.any():
        in_space[in_space] &= unique_idx[pos[in_space]] == u[in_space]

    r_in_norm_sq = 0.0
    if in_space.any():
        r_vals = w[in_space] - E * coeffs[pos[in_space]]
        r_in_norm_sq = float(np.sum(np.abs(r_vals) ** 2))

    out_mask = ~in_space
    r_out_idx = u[out_mask]
    r_out_vals = w[out_mask]

    return np.sqrt(r_in_norm_sq), r_out_idx, r_out_vals


def compute_residual_incremental(coeffs, unique_idx, H_cols, E, gpu_argsort=None,
                                  residual_chunk=50_000_000,
                                  apply_fn=None, hd_fn=None, db=None,
                                  az_of=None, bz_of=None, rt_a=None, rt_b=None):
    """Incremental residual via cached H columns, optimized pre-allocated chunked processing.

    H_cols[D] = (target_idx, value) stores the in-space H|D⟩ targets, cached at
    H-matrix construction time.  The in-space residual is a column linear
    combination merged with numpy concatenate + argsort + reduceat.

    If apply_fn is provided, out-of-space targets are recomputed via apply_fn
    (H_cols only caches in-space targets to save memory; ~90% of targets are
    out-of-space for small variational spaces).

    [优化三] 分块残差计算（chunked residual）：
    - 大系统（n_orb=44）4000 态 × 5.3万输出 = 2.13亿元素，超过 GPU argsort max_n
    - 将态分成小块，每块输出 < residual_chunk，分别用 GPU argsort + reduceat 合并
    - 收集各块合并结果后，最终再合并一次（唯一 target 数远小于总输出数）
    - 避免回退 CPU argsort（2亿元素 CPU argsort 需 30-40s），残差从 64s 降到 ~10s

    [优化一] 用 argsort + reduceat 代替 np.unique + add.at：
    - np.unique(return_inverse=True) 对 1340 万元素需 2.5s
    - argsort + reduceat 只需 1.8s（int32）/ 2.1s（int64），加速 1.2-1.5x

    [优化二] GPU argsort（稳定 radix sort 携带 index）：
    - 1340 万元素：CPU argsort 1.0s → GPU 0.25s，残差整体 1.8s→0.59s，加速 3x
    - 仅支持 int32（max<2^31），int64 回退 CPU
    - 需传入 gpu_argsort 对象（GPUArgsort 类）"""
    n = len(unique_idx)
    GPU_SAFE_LIMIT = 50_000_000  # GPU radix sort stable up to ~60M

    def _merge(targets, values):
        """Argsort + reduceat merge. Returns (unique_targets, merged_values)."""
        N = len(targets)
        if N == 0:
            return targets, values
        if targets.max() < (1 << 31):
            t_sort = targets.astype(np.int32)
            use_i32 = True
        else:
            t_sort = targets
            use_i32 = False

        use_gpu = (gpu_argsort is not None and N > 10000
                   and N <= gpu_argsort.max_n and N <= GPU_SAFE_LIMIT)
        if use_gpu:
            from geoqc.gpu import GPUArgsort, GPUArgsort64
            if use_i32 and isinstance(gpu_argsort, GPUArgsort):
                t_s, s_idx = gpu_argsort.argsort(t_sort)
                v_s = values[s_idx]
            elif (not use_i32) and isinstance(gpu_argsort, GPUArgsort64):
                t_s, s_idx = gpu_argsort.argsort(t_sort)
                if s_idx.max() >= N or s_idx.min() < 0:
                    order = np.argsort(t_sort)
                    t_s = t_sort[order]
                    v_s = values[order]
                else:
                    v_s = values[s_idx]
            else:
                order = np.argsort(t_sort)
                t_s = t_sort[order]
                v_s = values[order]
        else:
            order = np.argsort(t_sort)
            t_s = t_sort[order]
            v_s = values[order]

        diff = np.empty(N, dtype=bool)
        diff[0] = True
        diff[1:] = t_s[1:] != t_s[:-1]
        u = t_s[diff]
        bounds = np.nonzero(diff)[0]
        w = np.add.reduceat(v_s, bounds)
        return u.astype(np.int64), w

    # Chunked collection: collect states until chunk full, then merge immediately
    # This avoids huge memory allocation (proven 5.6x faster than single concatenate)
    chunk_t = []
    chunk_v = []
    chunk_size = 0
    all_u = []
    all_w = []

    for j in range(n):
        c = coeffs[j]
        if c == 0.0:
            continue
        t_idx, t_val = H_cols[int(unique_idx[j])]
        chunk_t.append(t_idx)
        chunk_v.append(c * t_val)
        chunk_size += len(t_idx)

        if chunk_size >= residual_chunk:
            ct = np.concatenate(chunk_t)
            cv = np.concatenate(chunk_v)
            u, w = _merge(ct, cv)
            all_u.append(u)
            all_w.append(w)
            chunk_t = []
            chunk_v = []
            chunk_size = 0

    if chunk_t:
        ct = np.concatenate(chunk_t)
        cv = np.concatenate(chunk_v)
        u, w = _merge(ct, cv)
        all_u.append(u)
        all_w.append(w)

    # Final cross-chunk merge
    if all_u:
        u, w = _merge(np.concatenate(all_u), np.concatenate(all_w))
    else:
        return 0.0, np.array([], dtype=np.int64), np.array([], dtype=np.float64)

    # Separate in-space and out-of-space
    pos = np.searchsorted(unique_idx, u)
    in_space = pos < n
    if in_space.any():
        in_space[in_space] &= unique_idx[pos[in_space]] == u[in_space]

    r_in_norm_sq = 0.0
    if in_space.any():
        r_vals = w[in_space] - E * coeffs[pos[in_space]]
        r_in_norm_sq = float(np.sum(r_vals ** 2))

    out_mask = ~in_space
    r_out_idx = u[out_mask]
    r_out_vals = w[out_mask]

    return np.sqrt(r_in_norm_sq), r_out_idx, r_out_vals


def compute_pt2_correction(r_out_idx, r_out_vals, E0, apply_fn, hd_fn, db,
                            az_of, bz_of, rt_a, rt_b,
                            top_n=50000, chunk_size=200):
    """PT2 energy correction (Epstein-Nesbet, diagonal approximation).

    E_PT2 = sum_{D not in V} |r_D|^2 / (E0 - H_DD)

    Geometric interpretation: this is the diagonal approximation of the
    normal-Hessian correction E_corr = -<r| (P_out H P_out - E0 I)^{-1} |r>,
    where r = P_out H|psi> is the normal residual vector on the Grassmannian.
    The full inverse is infeasible at dim=10^15; the diagonal approximation
    (Epstein-Nesbet PT2) is the standard first step.

    Only the top-N residual determinants are evaluated (PT2 is dominated by
    large residuals; tail contribution is negligible).

    Key optimisation: diagonal elements are identified by DIRECT BITSTRING
    COMPARISON (t_az == source_az AND t_bz == source_bz), avoiding the
    extremely expensive RankTable.rank() call (which does np.argsort on a
    (n, n_orb) matrix — 2GB temporary memory per chunk at n=2.5M).

    Parameters
    ----------
    r_out_idx : (M,) int array — out-of-space determinant combined indices
    r_out_vals : (M,) float array — residual values r_D = <D|H|psi>
    E0 : float — current variational energy
    apply_fn : callable — sparse action (includes two-body diagonal)
    hd_fn : callable — one-body diagonal + nuc lookup
    db, az_of, bz_of : rank lookup tables (rt_a/rt_b NOT needed)
    top_n : int — number of top residual determinants (default 50k)
    chunk_size : int — apply_fn batch size (default 200, ~10M outputs/batch)

    Returns
    -------
    E_pt2 : float — PT2 energy correction (should be negative)
    n_evaluated : int — number of determinants actually evaluated
    """
    import gc as _gc

    n_out = len(r_out_idx)
    if n_out == 0:
        return 0.0, 0

    # Select top-N by |r_D| using argpartition (O(n), not full sort O(n log n))
    if n_out > top_n:
        top_idx = np.argpartition(-np.abs(r_out_vals), top_n)[:top_n]
        eval_idx = r_out_idx[top_idx]
        eval_r = r_out_vals[top_idx]
    else:
        eval_idx = r_out_idx
        eval_r = r_out_vals

    n_eval = len(eval_idx)
    pt2_sum = 0.0

    # Chunked apply_fn to compute H_DD (avoid output buffer overflow)
    for c0 in range(0, n_eval, chunk_size):
        c1 = min(c0 + chunk_size, n_eval)
        chunk_idx = eval_idx[c0:c1]
        chunk_r = eval_r[c0:c1]
        n_chunk = len(chunk_idx)

        # Source bitstrings
        src_az = az_of[chunk_idx // db]
        src_bz = bz_of[chunk_idx % db]
        vals = np.ones(n_chunk, dtype=complex)
        result = apply_fn(src_az, src_bz, vals)
        if len(result) == 4:
            t_az, t_bz, t_v, src_idx = result
        else:
            t_az, t_bz, t_v = result
            per_src = len(t_az) // n_chunk
            src_idx = np.repeat(np.arange(n_chunk, dtype=np.int32), per_src)

        t_v_real = np.asarray(t_v).real

        # Diagonal elements: target bitstring == source bitstring.
        # DIRECT comparison — no RankTable.rank needed (avoids argsort
        # on (n, n_orb) matrix which was the memory/time bottleneck).
        diag_mask = ((t_az == src_az[src_idx]) &
                     (t_bz == src_bz[src_idx]))
        if diag_mask.any():
            diag_src = src_idx[diag_mask]   # local source of each diag term
            diag_v = t_v_real[diag_mask]    # two-body diag term value

            # A single source may have MULTIPLE diagonal terms (different
            # double-excitation paths ijab that return to D).  Accumulate
            # them per local source index with bincount.
            two_body_sum = np.bincount(diag_src, weights=diag_v,
                                        minlength=n_chunk)
            has_diag = two_body_sum != 0.0
            src_with_diag = np.where(has_diag)[0]

            # One-body diagonal + nuc added ONCE per source (not per term)
            one_body_diag = np.asarray(
                hd_fn(chunk_idx[src_with_diag])).real
            h_dd = two_body_sum[src_with_diag] + one_body_diag

            # PT2: |r_D|^2 / (E0 - H_DD)
            r_sq = chunk_r[src_with_diag] ** 2
            denom = E0 - h_dd
            denom = np.where(np.abs(denom) < 1e-8, 1e-8, denom)
            pt2_sum += float(np.sum(r_sq / denom))

        # Free chunk memory
        del t_az, t_bz, t_v, t_v_real, src_idx, result
        del src_az, src_bz, vals, chunk_idx, chunk_r
        if diag_mask.any():
            del diag_mask, diag_src, diag_v, two_body_sum, has_diag
            del src_with_diag, one_body_diag, h_dd
        _gc.collect()

    return pt2_sum, n_eval


# ---------------------------------------------------------------------------
# Block (geometric) normal-Hessian correction — article 10.91 §6 eq (6.3)
# ---------------------------------------------------------------------------

def _gather_residual(local_idx, r_out_idx, r_out_vals):
    """Residual values on local_idx via sorted searchsorted; 0 where absent."""
    r_block = np.zeros(len(local_idx), dtype=float)
    if len(r_out_idx) == 0:
        return r_block
    pos = np.searchsorted(r_out_idx, local_idx)
    pc = np.clip(pos, 0, len(r_out_idx) - 1)
    match = r_out_idx[pc] == local_idx
    r_block[match] = r_out_vals[pc[match]]
    return r_block


def compute_block_pt2_correction(r_out_idx, r_out_vals, E0, apply_fn, hd_fn,
                                 db, az_of, bz_of, rt_a, rt_b,
                                 in_space_idx=None, n_centers=20,
                                 h_build_chunk=200, verbose=False):
    """Geometric block-Newton normal-Hessian correction (10.91 Lemma D, eq 6.3).

    The diagonal PT2 (compute_pt2_correction) treats every out-of-space
    determinant as independent:  H_N = Q(H-E0)Q is replaced by its diagonal.
    Here we use the Bruhat locality of H (10.88 Prop 2.03: a non-zero entry
    needs Bruhat distance <=2): the normal space is partitioned into disjoint
    Bruhat 2-balls centred on the largest-residual determinants, and within
    each ball the FULL dense normal-Hessian block is inverted, capturing all
    intra-ball single/double-excitation couplings:

        E_corr = -sum_k r_k^T (H_block_k - E0 I)^{-1} r_k.

    Balls are made disjoint by greedy first-come assignment; determinants
    already in the variational space V are excluded (normal space = V perp).
    Inter-ball coupling exists only between balls whose centres are at
    Bruhat distance 3-4 (zero when >4); it is left for block-Jacobi sweeps
    (10.91 §9.1, convergence iff rho(D^-1 O)<1).  One call = one block-diagonal
    sweep (the dominant term); jacobi iteration is added on top after
    validation.

    Parameters
    ----------
    r_out_idx, r_out_vals : out-of-space residual; r_out_idx sorted ascending
        (as returned by compute_residual_incremental).
    E0 : current variational energy.
    in_space_idx : sorted combined indices of V; ball members in V are dropped.
    n_centers : number of Bruhat-ball centres = top residual determinants.
    h_build_chunk : chunk size handed to build_H_matrix for each block.
    verbose : print per-block diagnostics.

    Returns
    -------
    E_block : float — block-Newton correction.  On a positive-definite
        diagonally-dominant H_N the rigorous ordering (LiH/6-31G machine
        verified, article 10.91 §10) is
            |exact 2nd-order| <= |block| <= |diagonal EN-PT2|,
        i.e. intra-block coupling REDUCES the 2nd-order response, so the
        block value is slightly LESS negative than diagonal PT2 and converges
        to the exact Schur-complement value as the balls cover the normal
        space.  Diagonal EN-PT2 OVER-corrects (its H_DD denominator implicitly
        sums some higher-order terms); this happens to cancel high-order
        error at LARGE residual (small V), but at SMALL residual (near
        convergence, where the stopping decision is made) the unbiased block
        value is strictly more accurate — LiH |V|=488: block/exact-2nd error
        0.0000 mHa vs diagonal 0.0002 mHa (16x).  Inter-block residual is
        ~1e-7 relative (rho(D^-1 O)~0.12-0.17), removable to machine precision
        in 2-3 block-Jacobi sweeps (10.91 §9.1); one block-diagonal pass is
        already far below chemical accuracy for large systems.
    info : dict — n_blocks, block_sizes, n_assigned, residual_coverage
        (fraction of total |r|^2 inside the chosen blocks), block_E per block,
        assigned_idx (sorted global indices), block_members (per-block global
        indices, used to drive block-Jacobi).
    """
    n_out = len(r_out_idx)
    info = {"n_blocks": 0, "block_sizes": [], "block_E": [],
            "n_assigned": 0, "residual_coverage": 0.0,
            "assigned_idx": None, "block_members": []}
    if n_out == 0:
        return 0.0, info

    r_out_idx = np.asarray(r_out_idx)
    r_out_vals = np.asarray(r_out_vals, dtype=float)

    # --- 1. centres = top-n_centers residual determinants (argpartition) ---
    nc = min(n_centers, n_out)
    if n_out > nc:
        centre_sel = np.argpartition(-np.abs(r_out_vals), nc - 1)[:nc]
    else:
        centre_sel = np.arange(nc)
    centres = r_out_idx[centre_sel]

    v_set = set(int(x) for x in np.asarray(in_space_idx)) \
        if in_space_idx is not None else set()
    assigned = set()
    blocks = []

    # --- 2. enumerate each Bruhat 2-ball and assign disjoint members --------
    for C in centres:
        u, _ = apply_H(np.array([1.0 + 0j]), np.array([int(C)]),
                       apply_fn, hd_fn, db, az_of, bz_of, rt_a, rt_b)
        local = [int(x) for x in u.tolist()
                 if x not in v_set and x not in assigned]
        if not local:
            continue
        local = np.unique(np.asarray(local, dtype=np.int64))
        assigned.update(local.tolist())
        blocks.append(local)

    # --- residual-weight coverage of the chosen disjoint blocks ------------
    total_rsq = float(np.sum(r_out_vals ** 2))
    if total_rsq > 0:
        covered = np.array([x for x in r_out_idx.tolist() if x in assigned])
        if len(covered):
            info["residual_coverage"] = float(
                np.sum(_gather_residual(
                    np.unique(covered), r_out_idx, r_out_vals) ** 2)
                / total_rsq)

    # --- 3. per-block dense normal-Hessian inversion ------------------------
    E_block = 0.0
    eye_cache = {}
    for k, local in enumerate(blocks):
        Hb = build_H_matrix(local, apply_fn, hd_fn, db, az_of, bz_of,
                            rt_a, rt_b, H_cols=None, chunk_size=h_build_chunk)
        m = len(local)
        if m not in eye_cache:
            eye_cache[m] = np.eye(m)
        Hn = Hb - E0 * eye_cache[m]
        rb = _gather_residual(local, r_out_idx, r_out_vals)
        # Solve Hn x = rb (Hn real symmetric); robust fallback via eigh if
        # the block is (near-)singular.
        try:
            x = np.linalg.solve(Hn, rb)
        except np.linalg.LinAlgError:
            w, V = np.linalg.eigh(Hn)
            winv = 1.0 / np.where(np.abs(w) < 1e-10, 1e-10, w)
            x = V @ (winv * (V.T @ rb))
        ek = -float(rb @ x)
        E_block += ek
        info["block_sizes"].append(m)
        info["block_E"].append(ek)
        info["block_members"].append(local.copy())
        if verbose:
            print(f"    block {k}: size={m}, E_corr={ek:+.8f}, "
                  f"|r_block|={np.linalg.norm(rb):.6f}")
        del Hb, Hn, rb, x
        import gc; gc.collect()

    info["n_blocks"] = len(blocks)
    info["n_assigned"] = len(assigned)
    info["assigned_idx"] = (np.sort(np.asarray(sorted(assigned),
                                               dtype=np.int64))
                            if assigned else np.array([], dtype=np.int64))
    return E_block, info


# ---------------------------------------------------------------------------
# WCI main iteration
# ---------------------------------------------------------------------------

def wci(apply_fn, hd_fn, seed_idx, db, az_of, bz_of, rt_a, rt_b,
        max_wavepackets=30, tol=1e-6, verbose=True,
        select_weighted=False, hd_full_fn=None, energy_tol=None,
        use_gpu=False, gpu_argsort=None, max_wp_size=None,
        h_build_chunk=500, residual_chunk=80_000_000,
        select_geometric=False, geometric_alpha=1.0,
        select_ball_cover=False, ball_cover_topk=100,
        compute_pt2=False, pt2_top_n=50000, pt2_chunk=200,
        return_final_residual=False):
    """Wavepacket Configuration Interaction.

    Parameters
    ----------
    apply_fn : callable
        The sparse action from exterior.sparse_action_sz (vectorised single
        + double excitations, two-body diagonal included).
    hd_fn : callable
        One-body diagonal lookup (sector_diagonal_sz array for small dim,
        sector_diagonal_at for large dim).  Must have two_body=False.
    seed_idx : int
        The first wavepacket centre (typically the HF determinant).
    db : int
        Beta-sector dimension (combined index = alpha_rank * db + beta_rank).
    az_of, bz_of, rt_a, rt_b : arrays
        Rank tables from build_rank_tables.
    max_wavepackets : int
        Maximum number of wavepackets (iterations).
    tol : float
        Convergence tolerance on out-of-space residual norm (||r_out|| < tol
        AND energy change < tol).  For large systems where residual converges
        much slower than energy, use energy_tol instead.
    energy_tol : float | None
        If set, converge when |ΔE| < energy_tol (energy-change criterion),
        regardless of residual norm.  WCI energy converges much faster than
        residual: for chemical accuracy (1 kcal/mol = 1.59 mHa), use
        energy_tol=1e-4 (0.1 mHa, 16× tighter than chemical precision).
        This avoids the residual-norm bottleneck on large systems (H2O/cc-pVDZ:
        ||r_out||=0.26 at 7 wavepackets but energy already within ~0.6 mHa
        of FCI).
    verbose : bool
        Print per-iteration diagnostics.
    select_weighted : bool
        If True, select the new wavepacket centre by the energy-optimal
        (denominator-weighted) criterion argmax |<D|r>|^2 / |<D|H|D> - E|
        (命题 10.88.3.03/3.04, CIPSI-style) instead of the plain
        argmax |<D|r>|.  Requires hd_full_fn (full diagonal incl. two-body
        and nuclear repulsion).
    hd_full_fn : callable | None
        Full-diagonal lookup hd_full_fn(idxs) -> <D|H|D> (two_body=True),
        used only when select_weighted=True.
    use_gpu : bool
        If True, use GPU-accelerated matvec (OpenCL on AMD RX 570) for
        diagonalization. H matrix is transferred to GPU each iteration.
        2.5-3.0x speedup for V > 5000; slower for small V due to transfer
        overhead. Requires PyOpenCL and an AMD GPU.
    select_geometric : bool
        If True, select the new wavepacket centre by the geometric
        (Bruhat-distance weighted) criterion:
            score(D) = |r_D|^2 / (1 + α · min_{D'∈centres} bruhat_dist(D,D'))
        This penalises candidates that lie close to already-selected centres
        (their Bruhat 2-balls heavily overlap, adding little new information).
        Fixes the "false convergence" problem where CIPSI-style argmax |r_D|
        repeatedly selects overlapping wavepackets.  α=0 recovers plain CIPSI.
    geometric_alpha : float
        Overlap-penalty strength α in the geometric selection criterion
        (only used when select_geometric=True).  Larger α enforces more
        geometric diversity; recommended range 0.5–3.0.  Default 1.0.
    select_ball_cover : bool
        If True, select the new wavepacket centre by the fully-geometric
        Bruhat-ball greedy-cover criterion:
            score(D) = |r_D|^2 * (1 - |B(D,2) ∩ V| / |B(D,2)|)
        where V is the existing variational space.  This picks the Bruhat
        ball covering the largest *uncovered* residual weight, instead of
        CIPSI's argmax |r_D| (pick a point).  This is the geometric cure
        for "false convergence": a point with large residual but lying
        inside an already-covered ball adds little new information; the
        ball-cover score naturally penalises such picks.
        Priority: ball_cover > geometric > weighted > plain.
    ball_cover_topk : int
        Number of top residual candidates to evaluate for ball-cover
        selection (default 100).  Each candidate requires one apply_fn to
        compute its Bruhat ball support; larger top_k is more accurate but
        slower.
    compute_pt2 : bool
        If True, compute Epstein-Nesbet PT2 energy correction after each
        iteration: E_PT2 = sum_{D not in V} |r_D|^2 / (E0 - H_DD).
        This is the diagonal approximation of the geometric normal-Hessian
        correction E_corr = -<r| (P_out H P_out - E0 I)^{-1} |r>.
        PT2 gives a much better estimate of the true correlation energy
        than the variational energy alone, often reaching chemical accuracy
        with far fewer wavepackets.
    pt2_top_n : int
        Number of top residual determinants to evaluate for PT2 (default
        100k).  PT2 is dominated by large residuals; tail contribution is
        negligible.  Larger top_n is more accurate but slower.
    pt2_chunk : int
        apply_fn batch size for PT2 H_DD computation (default 500).
        Smaller chunks avoid output buffer overflow; larger chunks are
        faster but use more memory.

    Returns
    -------
    E : float
        Converged ground-state energy.
    unique_idx : ndarray
        Final variational space (sorted determinant indices).
    coeffs : ndarray
        Ground-state eigenvector coefficients in the variational space.
    wavepackets : list[Wavepacket]
        All wavepackets added during the iteration.
    history : list[tuple]
        (n_var, E, r_in_norm, r_out_norm) per iteration.
    """
    t_start = time.time()
    wavepackets = [Wavepacket(seed_idx, apply_fn, hd_fn, db, az_of, bz_of,
                               rt_a, rt_b, max_size=max_wp_size)]
    if verbose:
        print(f'  WP  1: center={wavepackets[0].center}, '
              f'size={wavepackets[0].size}')

    E_prev = None
    history = []
    H_mat_prev = None
    unique_idx_prev = None
    H_cols = {}  # cached full H|D⟩ columns for incremental residual
    selected_centers = [int(seed_idx)]  # for geometric (Bruhat-distance) selection
    # Last-iteration out-of-space residual (returned when return_final_residual)
    final_r_out_idx = np.array([], dtype=np.int64)
    final_r_out_vals = np.array([], dtype=np.float64)

    for iteration in range(max_wavepackets):
        # 1. variational space (cumulative union of wavepacket supports)
        unique_idx = build_variational_space(wavepackets)
        n_var = len(unique_idx)

        # 2. Rayleigh-Ritz (incremental H build + column caching)
        t0 = time.time()
        if H_mat_prev is not None and unique_idx_prev is not None:
            H_mat = build_H_incremental(
                unique_idx, unique_idx_prev, H_mat_prev,
                apply_fn, hd_fn, db, az_of, bz_of, rt_a, rt_b, H_cols)
        else:
            H_mat = build_H_matrix(
                unique_idx, apply_fn, hd_fn, db, az_of, bz_of, rt_a, rt_b,
                H_cols, chunk_size=h_build_chunk)

        # GPU-accelerated diagonalization (if enabled and V large enough)
        gpu_H = None
        if use_gpu and n_var > DAVIDSON_MIN_DIM:
            try:
                from geoqc.gpu import GPUMatrix
                gpu_H = GPUMatrix(H_mat)
            except Exception as e:
                if verbose:
                    print(f'  [GPU] Falling back to CPU: {e}')
                gpu_H = None

        E, coeffs = _eigh_ground(H_mat, gpu_H=gpu_H)
        if gpu_H is not None:
            gpu_H.release()
        t_h = time.time() - t0

        # 3. residual (incremental: cached column linear combination)
        t0 = time.time()
        r_in_norm, r_out_idx, r_out_vals = compute_residual_incremental(
            coeffs, unique_idx, H_cols, E, gpu_argsort=gpu_argsort,
            residual_chunk=residual_chunk,
            apply_fn=apply_fn, hd_fn=hd_fn, db=db,
            az_of=az_of, bz_of=bz_of, rt_a=rt_a, rt_b=rt_b)
        r_out_norm = (np.linalg.norm(r_out_vals)
                      if len(r_out_vals) > 0 else 0.0)
        # keep the latest out-of-space residual for block-Newton post-pass
        final_r_out_idx = r_out_idx
        final_r_out_vals = r_out_vals
        t_r = time.time() - t0

        # 3b. PT2 energy correction (Epstein-Nesbet, diagonal approximation)
        #     Geometric: normal-Hessian correction on the Grassmannian
        #     E_PT2 = sum |r_D|^2 / (E0 - H_DD) — much better energy estimate
        E_pt2 = 0.0
        E_corrected = E
        if compute_pt2 and len(r_out_vals) > 0:
            t0_pt2 = time.time()
            E_pt2, n_pt2 = compute_pt2_correction(
                r_out_idx, r_out_vals, E, apply_fn, hd_fn, db,
                az_of, bz_of, rt_a, rt_b,
                top_n=pt2_top_n, chunk_size=pt2_chunk)
            E_corrected = E + E_pt2
            t_pt2 = time.time() - t0_pt2
        else:
            t_pt2 = 0.0
            n_pt2 = 0

        history.append((n_var, E, r_in_norm, r_out_norm))
        if verbose:
            pt2_str = (f'  E+PT2={E_corrected:.10f} (PT2={E_pt2:+.6f}, '
                        f'n={n_pt2}, {t_pt2:.1f}s)' if compute_pt2 else '')
            print(f'  iter {iteration+1:2d}: n_var={n_var:7d}  '
                  f'E={E:.10f}  ||r_in||={r_in_norm:.2e}  '
                  f'||r_out||={r_out_norm:.2e}  n_wp={len(wavepackets)}  '
                  f'H={t_h:.1f}s  r={t_r:.1f}s{pt2_str}')

        # 4. convergence check
        if E_prev is not None:
            dE = abs(E - E_prev)
            # Energy-change criterion (fast): converge when |ΔE| < energy_tol,
            # regardless of residual norm.  WCI energy converges much faster
            # than ||r_out|| on large systems.
            if energy_tol is not None and dE < energy_tol:
                if verbose:
                    print(f'  Converged (energy) at iter {iteration+1}: '
                          f'|ΔE|={dE:.2e} < {energy_tol:.2e}')
                break
            # Residual criterion (strict): both |ΔE| < tol and ||r_out|| < tol
            if dE < tol and r_out_norm < tol:
                if verbose:
                    print(f'  Converged at iter {iteration+1}')
                break
        E_prev = E
        H_mat_prev = H_mat
        unique_idx_prev = unique_idx
        if iteration == max_wavepackets - 1:
            break

        # 5. new wavepacket centre selection.
        #    Four criteria (priority: ball_cover > geometric > weighted > plain):
        #    (a) select_ball_cover: Bruhat-ball greedy-cover (FULLY GEOMETRIC)
        #        score(D) = |r_D|^2 * (1 - |B(D,2) ∩ V| / |B(D,2)|)
        #        — pick the ball covering the largest *uncovered* residual weight;
        #          the geometric cure for CIPSI's false convergence.
        #    (b) select_geometric: Bruhat-distance weighted score
        #        score(D) = |r_D|^2 / (1 + α · min bruhat_dist(D, centres))
        #        — penalises overlap with existing wavepackets (approximate);
        #    (c) select_weighted: denominator-weighted (CIPSI PT2 style)
        #        score(D) = |r_D|^2 / |H_DD - E|;
        #    (d) plain: argmax |r_D| (default, CIPSI-style).
        if len(r_out_vals) > 0:
            if select_ball_cover:
                # Fully-geometric Bruhat-ball greedy-cover selection
                t_sel = time.time()
                new_center, best_score, best_local = _ball_cover_select(
                    r_out_idx, np.abs(r_out_vals), apply_fn, unique_idx,
                    db, az_of, bz_of, rt_a, rt_b,
                    top_k=ball_cover_topk, batch_size=50)
                # Find the index in r_out_idx for verbose output
                best = int(np.where(r_out_idx == new_center)[0][0]) \
                    if np.any(r_out_idx == new_center) else 0
                if verbose:
                    print(f'  [ball_cover] top_k={ball_cover_topk}, '
                          f'score={best_score:.3e}, '
                          f'|r|={abs(r_out_vals[best]):.2e}, '
                          f'sel_time={time.time()-t_sel:.1f}s')
            elif select_geometric:
                # Geometric (Bruhat-distance weighted) selection
                r_sq = np.abs(r_out_vals) ** 2
                min_dist = _bruhat_dist_vec(
                    r_out_idx, np.array(selected_centers, dtype=np.int64),
                    db, az_of, bz_of)
                score = r_sq / (1.0 + geometric_alpha * min_dist.astype(float))
                best = int(np.argmax(score))
                new_center = int(r_out_idx[best])
                if verbose:
                    print(f'  [geometric] best |r|={abs(r_out_vals[best]):.2e}, '
                          f'min_bruhat_dist={min_dist[best]}, '
                          f'α={geometric_alpha}')
            elif select_weighted and hd_full_fn is not None:
                denom = hd_full_fn(r_out_idx) - E
                score = np.abs(r_out_vals) ** 2 / np.maximum(np.abs(denom),
                                                             1e-10)
                best = int(np.argmax(score))
                new_center = int(r_out_idx[best])
            else:
                best = int(np.argmax(np.abs(r_out_vals)))
                new_center = int(r_out_idx[best])
            selected_centers.append(new_center)
            new_wp = Wavepacket(new_center, apply_fn, hd_fn, db, az_of,
                                 bz_of, rt_a, rt_b, max_size=max_wp_size)
            wavepackets.append(new_wp)
            if verbose:
                print(f'  WP {len(wavepackets):2d}: center={new_center}, '
                      f'size={new_wp.size}, |r|={abs(r_out_vals[best]):.2e}')
        else:
            if verbose:
                print('  No residual outside space — fully converged')
            break

    if verbose:
        print(f'  WCI done in {time.time()-t_start:.1f}s: '
              f'n_wp={len(wavepackets)}, n_var={len(unique_idx)}, '
              f'E={E:.10f}')
    if return_final_residual:
        # extra final out-of-space residual for a geometric block-Newton
        # (10.91 §6) post-pass without recomputing H columns.
        return (E, unique_idx, coeffs, wavepackets, history,
                final_r_out_idx, final_r_out_vals)
    return E, unique_idx, coeffs, wavepackets, history
